[package]
name = "rabbit-test"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = { version = "0.3.30", default-features = false }
lapin = { version = "2.3.1", default-features = false }
tokio = { version = "1.35.1", default-features = false, features = ["rt", "rt-multi-thread"] }
